# Do not include in your live environment.
########################################################################

services:
  djangoapp:
    build: 
      dockerfile: ./Dockerfile-dev
    environment:
      DJANGO_MODE: dev
