# Generated by Django 4.1.3 on 2022-11-09 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_bulletingroup_remove_bulletinentry_group_and_more'), ('main', '0003_alter_bulletinentry_options_and_more'), ('main', '0004_generalsettings'), ('main', '0005_quotes_alter_generalsettings_options_and_more'), ('main', '0006_rename_quotes_quote_alter_quote_options'), ('main', '0007_quote_enabled_alter_quote_quote'), ('main', '0008_alter_quote_enabled'), ('main', '0009_remove_bulletinentry_bulletin_group_and_more'), ('main', '0010_alter_bulletinentry_bulletin_groups'), ('main', '0011_remove_bulletinentry_bulletin_groups'), ('main', '0012_bulletinmanager_bulletinentry_bulletin_groups_and_more'), ('main', '0013_remove_bulletinentry_bulletin_groups_and_more'), ('main', '0014_announcement_alter_bulletinentry_position'), ('main', '0015_generalsettings_logo_path_and_more'), ('main', '0016_alter_generalsettings_logo_path_and_more'), ('main', '0017_alter_generalsettings_logo_path_and_more'), ('main', '0018_alter_generalsettings_logo_path_and_more'), ('main', '0019_contact_alter_announcement_options'), ('main', '0020_contacttable_contact_contact_table'), ('main', '0021_contacttable_additional_notes_contacttable_position_and_more'), ('main', '0022_remove_contact_contact_list'), ('main', '0023_contacttable_raw_content'), ('main', '0024_activebulletinentry_alter_bulletinentry_options_and_more'), ('main', '0025_announcement_name_alter_announcement_content'), ('main', '0026_alter_announcement_name'), ('main', '0027_generalsettings_ward_name'), ('main', '0028_alter_generalsettings_logo_path_and_more'), ('main', '0029_generalsettings_subscribe_email_and_more'), ('main', '0030_alter_generalsettings_logo_path_and_more'), ('main', '0031_generalsettings_homepage_photo_and_more'), ('main', '0032_generalsettings_image_upload'), ('main', '0033_remove_generalsettings_image_upload_and_more'), ('main', '0034_alter_generalsettings_homepage_quote'), ('main', '0035_alter_generalsettings_alternate_homepage_photo'), ('main', '0036_meetingtime_meetinghouse_address'), ('main', '0037_alter_generalsettings_alternate_homepage_photo'), ('main', '0038_bulletinentry_raw_content')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Determines if the group should be displayed or not. Only the first enabled group will be displayed.')),
                ('name', models.CharField(help_text='The name of the bulletin group. It is only to help you keep track of what entries the group contains, so choose anything you like.', max_length=255)),
            ],
            options={
                'verbose_name': 'Bulletin Group',
                'verbose_name_plural': 'Bulletin Groups',
            },
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_meeting_date', models.DateField(blank=True, help_text='Optional. The website automatically displays the next Sunday for the meeting date.\n\t\t\tSet a value here to override the next meeting date.', null=True)),
                ('first_hour_meeting_time', models.CharField(help_text='Required. Your Sacrament Meeting meeting time.', max_length=8)),
                ('second_hour_meeting_time', models.CharField(help_text='Required. Your classes meeting time.', max_length=8)),
                ('meetinghouse_address', models.TextField(blank=True, help_text='Optional. Will display on the homepage if entered. Try and format it using 2-3 lines of text.')),
            ],
            options={
                'verbose_name': 'Meeting Times',
                'verbose_name_plural': 'Meeting Times',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Required. The source of the quote.', max_length=128)),
                ('quote', models.TextField(help_text='Required. The quote content.')),
                ('url', models.CharField(blank=True, default='', help_text='Optional. The optional URL of the quote. If included, will add a hyperlink to the source field under the quote on the program page.', max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='Determines if the quote should be added to the display rotation.')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.CreateModel(
            name='BulletinEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Determines if the row should be displayed on the page.')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='The order the entry appears within the group. Leave blank to auto-fill with next value.', null=True)),
                ('title', models.CharField(help_text='Required. Without a value, will center on the page. With a value included, will be left-justified.', max_length=128)),
                ('value', models.CharField(blank=True, default='', help_text='Optional. If added, will right-justify in-line with the (now left-justified) title.', max_length=128)),
                ('url', models.CharField(blank=True, help_text='Optional. If added, will add a hyperlink to the Value field.', max_length=255, null=True, verbose_name='URL')),
                ('section', models.PositiveSmallIntegerField(choices=[(1, 'Sacrament Meeting'), (2, 'Sunday School'), (3, 'Relief Society and Priesthood')], default=1, help_text='Required. The page section to appear in.')),
                ('additional_note', models.CharField(blank=True, default='', help_text='Optional. If included, will show up to the right of the Value field, outside the hyperlink (for example, the hymn number next to the hymn name).', max_length=128)),
                ('bulletin_group', models.ForeignKey(blank=True, help_text='Optional. Select which Bulletin Group this entry belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletinEntries', to='main.bulletingroup')),
                ('raw_content', models.TextField(blank=True, help_text='Optional. Adding content here will override the default row,\n\t\tand the rest of the fields will be ignored. Supports Markdown and HTML.')),
            ],
            options={
                'verbose_name': 'Bulletin Entry',
                'verbose_name_plural': 'All Bulletin Entries',
            },
        ),
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Determines if the group should be displayed or not.')),
                ('name', models.CharField(help_text='Required. The name of the contact group. It will appear above the table on the webpage.', max_length=255)),
                ('additional_notes', models.TextField(blank=True, help_text='Optional. Additional notes that will appear below the table on the webpage if set.')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='The order the table appears on the page. Leave blank to auto-fill with next value.', null=True)),
                ('raw_content', models.TextField(blank=True, help_text='Optional. Adding content here will override the default table layout. Supports\n\t\tMarkdown and HTML.')),
            ],
            options={
                'verbose_name': 'Contact Table',
                'verbose_name_plural': 'Contact Tables',
            },
        ),
        migrations.CreateModel(
            name='ActiveBulletinEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Active Bulletin Entry',
                'verbose_name_plural': 'Active Bulletin Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.bulletinentry',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Required. The contact's name.", max_length=128)),
                ('email', models.EmailField(blank=True, help_text="Optional. The contact's email address.", max_length=254)),
                ('phone', models.CharField(blank=True, help_text="Optional. The contact's phone number.", max_length=20)),
                ('calling', models.CharField(help_text="Required. The contact's calling.", max_length=128)),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='The position of the contact in the table on the page. Leave blank to auto-fill with next value.', null=True)),
                ('contact_table', models.ForeignKey(blank=True, help_text='Optional. Select which Contact Table this contact belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.contacttable')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'All Contacts',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Determines if the announcement should be displayed on the announcements page.')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='The order the announcement appears on the page. Leave blank to auto-fill with next value.', null=True)),
                ('content', models.TextField(help_text='Required. Supports markdown formatting')),
                ('name', models.CharField(help_text='Required. Helps you organize your announcments internally.', max_length=128)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.PositiveSmallIntegerField(choices=[(1, 'Slate'), (2, 'Gray'), (3, 'Zinc'), (4, 'Neutral'), (5, 'Stone'), (6, 'Brown'), (7, 'Red'), (8, 'Orange'), (9, 'Amber'), (10, 'Yellow'), (11, 'Lime'), (12, 'Green'), (13, 'Emerald'), (14, 'Teal'), (15, 'Cyan'), (16, 'Sky'), (17, 'Blue'), (18, 'Indigo'), (19, 'Violet'), (20, 'Purple'), (21, 'Fuchsia'), (22, 'Pink'), (23, 'Rose')], default=6, help_text='Website Theme Color')),
                ('logo_path', models.FilePathField(blank=True, help_text='Path to the logo displayed in the top-left corner of the webpage.\n\t\tIf not provided, the corner will be left blank.', path='/opt/services/djangoapp/static/main/images', recursive=True)),
                ('photos_path', models.FilePathField(allow_folders=True, blank=True, help_text='Path to the directory containing the photos that will be displayed\n\t\trandomly on the program page. If not provided, the quote will be lonely.', path='/opt/services/djangoapp/static/main/images', recursive=True)),
                ('ward_name', models.CharField(default='foo', help_text='Required. It will display at the top of the main page.', max_length=128)),
                ('subscribe_email', models.EmailField(blank=True, help_text='Optional. If you have a mid-week email list, add the contact here so people can subscribe.', max_length=254)),
                ('homepage_photo', models.FilePathField(blank=True, help_text='Path to the photo to be displayed on the homepage.\n\t\tIf not provided, the hompage will re-center the content without the image.', path='/opt/services/djangoapp/static/main/images', recursive=True)),
                ('homepage_quote', models.ForeignKey(blank=True, help_text='Select which quote in the quote table you want displayed under the picture on the homepage.\n\t\tDisabled quotes are allowed. If not provided, no quote will be displayed on the homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.quote')),
                ('alternate_homepage_photo', models.ImageField(blank=True, help_text='Upload a photo here to set an alternate photo for the homepage.', upload_to='media')),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
            },
        ),
    ]
