# Generated by Django 4.1.2 on 2022-10-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='If the row should be displayed or not.')),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Sacrament Meeting'), (2, 'Sunday School'), (3, 'Relief Society and Priesthood')], default=1, help_text='The page group to add to.')),
                ('position', models.PositiveSmallIntegerField(help_text='The sorting position on the page within the group.')),
                ('title', models.CharField(help_text='Without a value, will center on the page. With a value included, will be left-justified.', max_length=128)),
                ('value', models.CharField(blank=True, help_text='If added, will right-justify in-line with the (now left-justified) title.', max_length=128, null=True)),
                ('url', models.CharField(blank=True, help_text='If added, will hyperlink the value.', max_length=255, null=True)),
                ('hymn', models.PositiveSmallIntegerField(blank=True, help_text='If included, will add the hymn number next to the value.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_meeting_date', models.DateField(blank=True, help_text='The website automatically displays the next Sunday for the meeting date.Set a value here to override the next meeting date.', null=True)),
                ('first_hour_meeting_time', models.CharField(max_length=8)),
                ('second_hour_meeting_time', models.CharField(max_length=8)),
            ],
        ),
    ]
