# Generated by Django 4.1.3 on 2022-11-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='first_hour_meeting_time',
            field=models.CharField(help_text='Required. Your Sacrament Meeting meeting time.', max_length=8),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='second_hour_meeting_time',
            field=models.CharField(help_text='Required. Your classes meeting time.', max_length=8),
        ),
    ]
