# Generated by Django 4.1.2 on 2022-10-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='If the group should be displayed or not. Only the first enabled group will be displayed.')),
                ('name', models.CharField(help_text='The name of the bulletin entry group', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='bulletinentry',
            name='group',
        ),
        migrations.AddField(
            model_name='bulletinentry',
            name='section',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sacrament Meeting'), (2, 'Sunday School'), (3, 'Relief Society and Priesthood')], default=1, help_text='The page section to add to.'),
        ),
        migrations.AddField(
            model_name='bulletinentry',
            name='bulletinGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletinEntries', to='main.bulletingroup'),
        ),
    ]
