# Generated by Django 4.2.3 on 2023-07-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_generalsettings_first_hour_meeting_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Determines if the page should be displayed or not.')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='The order of the pages in the tab bar. Leave blank to auto-fill with next value.', null=True)),
                ('title', models.CharField(help_text='Required. Displayed in the tab bar.', max_length=128)),
                ('content', models.TextField(help_text='Required. Supports markdown formatting.')),
            ],
            options={
                'verbose_name': 'More Pages',
                'verbose_name_plural': 'More Pages',
            },
        ),
    ]
