# Generated by Django 4.1.2 on 2022-10-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bulletingroup_remove_bulletinentry_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletinentry',
            options={'verbose_name': 'Bulletin Entry', 'verbose_name_plural': 'Bulletin Entries'},
        ),
        migrations.AlterModelOptions(
            name='bulletingroup',
            options={'verbose_name': 'Bulletin Group', 'verbose_name_plural': 'Bulletin Groups'},
        ),
        migrations.AlterModelOptions(
            name='meetingtime',
            options={'verbose_name': 'Meeting Times', 'verbose_name_plural': 'Meeting Times'},
        ),
        migrations.RenameField(
            model_name='bulletinentry',
            old_name='bulletinGroup',
            new_name='bulletin_group',
        ),
        migrations.RemoveField(
            model_name='bulletinentry',
            name='hymn',
        ),
        migrations.AddField(
            model_name='bulletinentry',
            name='additional_note',
            field=models.CharField(blank=True, help_text='If included, will show up next to the value (for example, the hymn number).', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bulletinentry',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The sorting position on the page within the group. Leave blank to auto-fill with next value.', null=True),
        ),
    ]
