# Generated by Django 4.2.3 on 2023-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_morepages'),
    ]

    operations = [
        migrations.AddField(
            model_name='morepages',
            name='slug',
            field=models.SlugField(default='', help_text='Required. The URL of the page. Defaults to a slugified version of the title.'),
            preserve_default=False,
        ),
    ]
