# Generated by Django 4.1.2 on 2022-10-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bulletinentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.PositiveSmallIntegerField(choices=[(1, 'Slate'), (2, 'Gray'), (3, 'Zinc'), (4, 'Neutral'), (5, 'Stone'), (6, 'Brown'), (7, 'Red'), (8, 'Orange'), (9, 'Amber'), (10, 'Yellow'), (11, 'Lime'), (12, 'Green'), (13, 'Emerald'), (14, 'Teal'), (15, 'Cyan'), (16, 'Sky'), (17, 'Blue'), (18, 'Indigo'), (19, 'Violet'), (20, 'Purple'), (21, 'Fuchsia'), (22, 'Pink'), (23, 'Rose')], default=6, help_text='Website Theme Color')),
            ],
        ),
    ]
