# Generated by Django 4.1.2 on 2022-10-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_quotes_alter_generalsettings_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
    ]
