# Generated by Django 4.1.2 on 2022-10-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_quotes_quote_alter_quote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='enabled',
            field=models.BooleanField(default=False, help_text='If the quote should be displayed or not.'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(help_text='The quote content'),
        ),
    ]
