# Generated by Django 4.1.2 on 2022-10-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_quote_enabled_alter_quote_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='enabled',
            field=models.BooleanField(default=True, help_text='If the quote should be displayed or not.'),
        ),
    ]
