# Generated by Django 4.1.2 on 2022-10-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_quote_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletinentry',
            name='bulletin_group',
        ),
        migrations.AddField(
            model_name='bulletinentry',
            name='bulletin_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='bulletinEntries', to='main.bulletingroup'),
        ),
    ]
