# Generated by Django 4.1.2 on 2022-10-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_bulletinentry_bulletin_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinentry',
            name='bulletin_groups',
            field=models.ManyToManyField(blank=True, related_name='bulletinEntries', to='main.bulletingroup'),
        ),
    ]
