# Generated by Django 4.1.2 on 2022-10-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_bulletinentry_bulletin_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletinentry',
            name='bulletin_groups',
        ),
    ]
