# Generated by Django 4.1.2 on 2022-10-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_bulletinentry_bulletin_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bulletinentry')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bulletingroup')),
            ],
            options={
                'verbose_name': 'Bulletin Manager',
                'verbose_name_plural': 'Bulletin Managers',
            },
        ),
        migrations.AddField(
            model_name='bulletinentry',
            name='bulletin_groups',
            field=models.ManyToManyField(blank=True, related_name='bulletinEntries', through='main.BulletinManager', to='main.bulletingroup'),
        ),
        migrations.AddField(
            model_name='bulletingroup',
            name='bulletin_entries',
            field=models.ManyToManyField(blank=True, related_name='bulletinGroups', through='main.BulletinManager', to='main.bulletinentry'),
        ),
    ]
