# Generated by Django 4.1.2 on 2022-10-26 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bulletinmanager_bulletinentry_bulletin_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletinentry',
            name='bulletin_groups',
        ),
        migrations.RemoveField(
            model_name='bulletingroup',
            name='bulletin_entries',
        ),
        migrations.AddField(
            model_name='bulletinentry',
            name='bulletin_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletinEntries', to='main.bulletingroup'),
        ),
        migrations.DeleteModel(
            name='BulletinManager',
        ),
    ]
