# Generated by Django 4.1.2 on 2022-10-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_bulletinentry_bulletin_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='If the announcement should be displayed or not.')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='The order the announcement appears on the page. Leave blank to auto-fill with next value.', null=True)),
                ('content', models.TextField(help_text='Supports markdown formatting')),
            ],
        ),
        migrations.AlterField(
            model_name='bulletinentry',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The order the entry appears within the group. Leave blank to auto-fill with next value.', null=True),
        ),
    ]
