# Generated by Django 4.1.2 on 2022-10-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_announcement_alter_bulletinentry_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='logo_path',
            field=models.FilePathField(blank=True, help_text='Path to the logo displayed in the top-left corner of the webpage.\n\t\tIf not provided, the corner will be left blank.', path='/opt/services/djangoapp/src/static', recursive=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='photos_path',
            field=models.FilePathField(allow_folders=True, blank=True, help_text='Path to the directory containing the photos that will be displayed\n\t\trandomly on the homepage. If not provided, the quote will be lonely.', path='/opt/services/djangoapp/src/static', recursive=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Determines if the announcement should be displayed on the announcements page.'),
        ),
        migrations.AlterField(
            model_name='bulletinentry',
            name='additional_note',
            field=models.CharField(blank=True, default='', help_text='Optional. If included, will show up to the right of the Value field, outside the hyperlink (for example, the hymn number next to the hymn name).', max_length=128),
        ),
        migrations.AlterField(
            model_name='bulletinentry',
            name='bulletin_group',
            field=models.ForeignKey(blank=True, help_text='Optional. Select which Bulletin Group this entry belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletinEntries', to='main.bulletingroup'),
        ),
        migrations.AlterField(
            model_name='bulletinentry',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Determines if the row should be displayed on the page.'),
        ),
        migrations.AlterField(
            model_name='bulletinentry',
            name='section',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sacrament Meeting'), (2, 'Sunday School'), (3, 'Relief Society and Priesthood')], default=1, help_text='Required. The page section to appear in.'),
        ),
        migrations.AlterField(
            model_name='bulletinentry',
            name='title',
            field=models.CharField(help_text='Required. Without a value, will center on the page. With a value included, will be left-justified.', max_length=128),
        ),
        migrations.AlterField(
            model_name='bulletinentry',
            name='url',
            field=models.CharField(blank=True, help_text='Optional. If added, will add a hyperlink to the Value field.', max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='bulletinentry',
            name='value',
            field=models.CharField(blank=True, default='', help_text='Optional. If added, will right-justify in-line with the (now left-justified) title.', max_length=128),
        ),
        migrations.AlterField(
            model_name='bulletingroup',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Determines if the group should be displayed or not. Only the first enabled group will be displayed.'),
        ),
        migrations.AlterField(
            model_name='bulletingroup',
            name='name',
            field=models.CharField(help_text='The name of the bulletin group. It is only to help you keep track of what entries the group contains, so choose anything you like.', max_length=255),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='first_hour_meeting_time',
            field=models.CharField(help_text='Required. Your Sacrament Meeting meeting time.', max_length=8),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='next_meeting_date',
            field=models.DateField(blank=True, help_text='Optional. The website automatically displays the next Sunday for the meeting date.\n\t\t\tSet a value here to override the next meeting date.', null=True),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='second_hour_meeting_time',
            field=models.CharField(help_text='Required. Your classes meeting time.', max_length=8),
        ),
        migrations.AlterField(
            model_name='quote',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Determines if the quote should be added to the display rotation.'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(help_text='Required. The quote content.'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(help_text='Required. The source of the quote.', max_length=128),
        ),
        migrations.AlterField(
            model_name='quote',
            name='url',
            field=models.CharField(blank=True, default='', help_text='Optional. The optional URL of the quote. If included, will add a hyperlink to the source field under the quote on the homepage.', max_length=255),
        ),
    ]
