# Generated by Django 4.1.2 on 2022-10-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_generalsettings_logo_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Required. The contact's name.", max_length=128)),
                ('email', models.EmailField(blank=True, help_text="Optional. The contact's email address.", max_length=254)),
                ('phone', models.CharField(blank=True, help_text="Optional. The contact's phone number.", max_length=20)),
                ('calling', models.CharField(help_text="Required. The contact's calling.", max_length=128)),
                ('contact_list', models.PositiveSmallIntegerField(choices=[(1, 'Main Contacts'), (2, 'Other Contacts')], default=1, help_text='Required. The contact list to appear in.')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='The position of the contact in the table on the page. Leave blank to auto-fill with next value.', null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
    ]
