# Generated by Django 4.1.2 on 2022-10-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_contact_alter_announcement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Determines if the group should be displayed or not. Only the first enabled group will be displayed.')),
                ('name', models.CharField(help_text='The name of the contact group. It is only to help you keep track of what entries the group contains, so choose anything you like.', max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Table',
                'verbose_name_plural': 'Contact Tables',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_table',
            field=models.ForeignKey(blank=True, help_text='Optional. Select which Contact Table this contact belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.contacttable'),
        ),
    ]
