# Generated by Django 4.1.2 on 2022-10-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_contacttable_contact_contact_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttable',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Optional. Additional notes that will appear below the table on the webpage if set.'),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The order the table appears on the page. Leave blank to auto-fill with next value.', null=True),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Determines if the group should be displayed or not.'),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='name',
            field=models.CharField(help_text='Required. The name of the contact group. It will appear above the table on the webpage.', max_length=255),
        ),
    ]
