# Generated by Django 4.1.2 on 2022-10-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contacttable_additional_notes_contacttable_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_list',
        ),
    ]
