# Generated by Django 4.1.2 on 2022-10-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_contact_contact_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttable',
            name='raw_content',
            field=models.TextField(blank=True, help_text="If the default table layout doesn't work for what you need to display, you can use\n\t\tthis field to have full control over what gets displayed. You can put markdown or HTML into this\n\t\tfield and it will be displayed directly. Any Contacts associated with the table will be ignored,\n\t\tso you will need to add them manually to this field as well. \n\t\t[Learn more about markdown tables.](https://www.markdownguide.org/extended-syntax/#tables)"),
        ),
    ]
