# Generated by Django 4.1.2 on 2022-10-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_contacttable_raw_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveBulletinEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Active Bulletin Entry',
                'verbose_name_plural': 'Active Bulletin Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.bulletinentry',),
        ),
        migrations.AlterModelOptions(
            name='bulletinentry',
            options={'verbose_name': 'Bulletin Entry', 'verbose_name_plural': 'All Bulletin Entries'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'All Contacts'},
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='raw_content',
            field=models.TextField(blank=True, help_text='Optional. Adding content here will override the default table layout. Supports\n\t\tMarkdown and HTML.'),
        ),
    ]
