# Generated by Django 4.1.2 on 2022-10-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_activebulletinentry_alter_bulletinentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='name',
            field=models.CharField(blank=True, help_text='Optional. Helps you organize your announcments internally.', max_length=128),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(help_text='Required. Supports markdown formatting'),
        ),
    ]
