# Generated by Django 4.1.2 on 2022-10-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_announcement_name_alter_announcement_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.CharField(help_text='Required. Helps you organize your announcments internally.', max_length=128),
        ),
    ]
