# Generated by Django 4.1.2 on 2022-10-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_announcement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='ward_name',
            field=models.CharField(default='foo', help_text='Required. It will display at the top of the main page.', max_length=128),
            preserve_default=False,
        ),
    ]
