# Generated by Django 4.1.3 on 2022-11-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_generalsettings_homepage_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Use this to upload new photos for any of the photo pickers above.\n\t\tIf you have many photos to upload, it will likely be easier to provide the group\n\t\tof photos to your web administrator and they can upload them directly.', null=True, upload_to='main/images'),
        ),
    ]
