# Generated by Django 4.1.3 on 2022-11-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_generalsettings_image_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='image_upload',
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='alternate_homepage_photo',
            field=models.ImageField(blank=True, help_text='Upload a photo here to set an alternate photo for the homepage.', null=True, upload_to='main/images/upload'),
        ),
    ]
