# Generated by Django 4.1.3 on 2022-11-09 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_generalsettings_image_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='homepage_quote',
            field=models.ForeignKey(blank=True, help_text='Select which quote in the quote table you want displayed under the picture on the homepage.\n\t\tDisabled quotes are allowed. If not provided, no quote will be displayed on the homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.quote'),
        ),
    ]
