# Generated by Django 4.1.3 on 2022-11-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_generalsettings_alternate_homepage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtime',
            name='meetinghouse_address',
            field=models.TextField(blank=True, help_text='Optional. Will display on the homepage if entered. Try and format it using 2-3 lines of text.'),
        ),
    ]
