# Generated by Django 4.1.3 on 2022-11-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_generalsettings_alternate_homepage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinentry',
            name='raw_content',
            field=models.TextField(blank=True, help_text='Optional. Adding content here will override the default row,\n\t\tand the rest of the fields will be ignored. Supports Markdown and HTML.'),
        ),
    ]
