# Generated by Django 4.1.3 on 2022-11-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0038_bulletinentry_raw_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='alternate_homepage_photo',
            field=models.ImageField(blank=True, help_text='Upload a photo here to set an alternate photo for the homepage.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='ward_name',
            field=models.CharField(help_text='Required. It will display at the top of the main page.', max_length=128),
        ),
    ]
