# Generated by Django 4.1.3 on 2022-11-14 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_delete_meetingtime_remove_bulletinentry_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='The order the group will appear on the program if multiple groups are enabled', null=True)),
                ('enabled', models.BooleanField(default=False, help_text='Determines if the group should be displayed or not.')),
                ('title', models.CharField(help_text='The title for the class schedule group. It is displayed at the top of the list of classes on the program.', max_length=255)),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
            },
        ),
        migrations.CreateModel(
            name='ClassEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Determines if the row should be displayed on the page.')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='The order the entry appears within the group. Leave blank to auto-fill with next value.', null=True)),
                ('title', models.CharField(help_text='Required. Without a value, will center on the page. With a value included, will be left-justified.', max_length=128)),
                ('value', models.CharField(blank=True, default='', help_text='Optional. If added, will right-justify in-line with the (now left-justified) title.', max_length=128)),
                ('url', models.CharField(blank=True, help_text='Optional. If added, will add a hyperlink to the Value field.', max_length=255, null=True, verbose_name='URL')),
                ('additional_note', models.CharField(blank=True, default='', help_text='Optional. If included, will show up to the right of the Value field, outside the hyperlink (for example, the hymn number next to the hymn name).', max_length=128)),
                ('raw_content', models.TextField(blank=True, help_text='Optional. Adding content here will override the default row,\n\t\tand the rest of the fields will be ignored. Supports Markdown and HTML.')),
                ('class_schedule', models.ForeignKey(help_text='Required. Select which Bulletin Group this entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bulletinEntries', to='main.classschedule')),
            ],
            options={
                'verbose_name': 'Class Entry',
                'verbose_name_plural': 'All Class Entries',
            },
        ),
    ]
