# Generated by Django 4.1.3 on 2022-11-14 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_classschedule_classentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classentry',
            name='additional_note',
            field=models.CharField(blank=True, default='', help_text='Optional. If included, will show up to the right of the Value field, outside the hyperlink (for example, the class meeting location).', max_length=128),
        ),
        migrations.AlterField(
            model_name='classentry',
            name='class_schedule',
            field=models.ForeignKey(help_text='Required. Select which Class Schedule Group this entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='classEntries', to='main.classschedule'),
        ),
    ]
